name: awesome_project
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Design Pattern
  flutter_bloc: ^8.0.0
  rxdart: ^0.27.3

  # Common
  cupertino_icons: ^1.0.2
  retrofit: ^3.0.0
  equatable: ^2.0.3
  configuration:
    path: ./configuration
  flutter_screenutil: ^5.0.1+3

dev_dependencies:
  bloc_test: ^9.0.1
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.3
  mockito: ^5.0.17
  retrofit_generator: ^3.0.0+2

flutter:
  uses-material-design: true
